name: Rust

on:
  push:
    branches: [main]
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10

jobs:
  checks:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        toolchain:
        - 1.75.0
        - stable
    steps:
    - uses: actions/checkout@v4
    - uses: extractions/setup-just@v1
      with:
        just-version: 1.16.0
    - uses: Swatinem/rust-cache@v2
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.75.0
        components: clippy, rustfmt
        targets: x86_64-unknown-linux-gnu
    - name: Build
      run: just compile
    - name: Run tests
      run: just test
    - name: Lint
      run: just lint
